import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/providers/lenis-provider";
import Navigation from "@/components/global/navigation";
import Logo from "@/components/global/logo";
import Preloader from "@/components/global/preloader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground relative`}
			>
				<Preloader />
				<div
					className="pointer-events-none fixed inset-0 z-100 h-full w-full opacity-[0.03]"
					style={{
						zIndex: 100,
						backgroundImage:
							'url(\'data:image/svg+xml,%3Csvg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"%3E%3Cfilter id="noiseFilter"%3E%3CfeTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch"/%3E%3C/filter%3E%3Crect width="100%25" height="100%25" filter="url(%23noiseFilter)"/%3E%3C/svg%3E\')',
					}}
				></div>
				<Logo />
				<Navigation />
				<LenisProvider>{children}</LenisProvider>
			</body>
		</html>
	);
}
